// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CreateJoinRoomArgs.proto

#ifndef PROTOBUF_CreateJoinRoomArgs_2eproto__INCLUDED
#define PROTOBUF_CreateJoinRoomArgs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "KeyValuePair.pb.h"
// @@protoc_insertion_point(includes)

namespace EECloud {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_CreateJoinRoomArgs_2eproto();
void protobuf_AssignDesc_CreateJoinRoomArgs_2eproto();
void protobuf_ShutdownFile_CreateJoinRoomArgs_2eproto();

class CreateJoinRoomArgs;

// ===================================================================

class CreateJoinRoomArgs : public ::google::protobuf::Message {
 public:
  CreateJoinRoomArgs();
  virtual ~CreateJoinRoomArgs();
  
  CreateJoinRoomArgs(const CreateJoinRoomArgs& from);
  
  inline CreateJoinRoomArgs& operator=(const CreateJoinRoomArgs& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateJoinRoomArgs& default_instance();
  
  void Swap(CreateJoinRoomArgs* other);
  
  // implements Message ----------------------------------------------
  
  CreateJoinRoomArgs* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateJoinRoomArgs& from);
  void MergeFrom(const CreateJoinRoomArgs& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string RoomId = 1;
  inline bool has_roomid() const;
  inline void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  inline const ::std::string& roomid() const;
  inline void set_roomid(const ::std::string& value);
  inline void set_roomid(const char* value);
  inline void set_roomid(const char* value, size_t size);
  inline ::std::string* mutable_roomid();
  inline ::std::string* release_roomid();
  
  // optional string ServerType = 2;
  inline bool has_servertype() const;
  inline void clear_servertype();
  static const int kServerTypeFieldNumber = 2;
  inline const ::std::string& servertype() const;
  inline void set_servertype(const ::std::string& value);
  inline void set_servertype(const char* value);
  inline void set_servertype(const char* value, size_t size);
  inline ::std::string* mutable_servertype();
  inline ::std::string* release_servertype();
  
  // optional bool Visible = 3;
  inline bool has_visible() const;
  inline void clear_visible();
  static const int kVisibleFieldNumber = 3;
  inline bool visible() const;
  inline void set_visible(bool value);
  
  // repeated .EECloud.KeyValuePair RoomData = 4;
  inline int roomdata_size() const;
  inline void clear_roomdata();
  static const int kRoomDataFieldNumber = 4;
  inline const ::EECloud::KeyValuePair& roomdata(int index) const;
  inline ::EECloud::KeyValuePair* mutable_roomdata(int index);
  inline ::EECloud::KeyValuePair* add_roomdata();
  inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
      roomdata() const;
  inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
      mutable_roomdata();
  
  // repeated .EECloud.KeyValuePair JoinData = 5;
  inline int joindata_size() const;
  inline void clear_joindata();
  static const int kJoinDataFieldNumber = 5;
  inline const ::EECloud::KeyValuePair& joindata(int index) const;
  inline ::EECloud::KeyValuePair* mutable_joindata(int index);
  inline ::EECloud::KeyValuePair* add_joindata();
  inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
      joindata() const;
  inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
      mutable_joindata();
  
  // optional bool IsDevRoom = 6;
  inline bool has_isdevroom() const;
  inline void clear_isdevroom();
  static const int kIsDevRoomFieldNumber = 6;
  inline bool isdevroom() const;
  inline void set_isdevroom(bool value);
  
  // @@protoc_insertion_point(class_scope:EECloud.CreateJoinRoomArgs)
 private:
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_servertype();
  inline void clear_has_servertype();
  inline void set_has_visible();
  inline void clear_has_visible();
  inline void set_has_isdevroom();
  inline void clear_has_isdevroom();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* roomid_;
  ::std::string* servertype_;
  ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair > roomdata_;
  ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair > joindata_;
  bool visible_;
  bool isdevroom_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_CreateJoinRoomArgs_2eproto();
  friend void protobuf_AssignDesc_CreateJoinRoomArgs_2eproto();
  friend void protobuf_ShutdownFile_CreateJoinRoomArgs_2eproto();
  
  void InitAsDefaultInstance();
  static CreateJoinRoomArgs* default_instance_;
};
// ===================================================================


// ===================================================================

// CreateJoinRoomArgs

// optional string RoomId = 1;
inline bool CreateJoinRoomArgs::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateJoinRoomArgs::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateJoinRoomArgs::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateJoinRoomArgs::clear_roomid() {
  if (roomid_ != &::google::protobuf::internal::kEmptyString) {
    roomid_->clear();
  }
  clear_has_roomid();
}
inline const ::std::string& CreateJoinRoomArgs::roomid() const {
  return *roomid_;
}
inline void CreateJoinRoomArgs::set_roomid(const ::std::string& value) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(value);
}
inline void CreateJoinRoomArgs::set_roomid(const char* value) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(value);
}
inline void CreateJoinRoomArgs::set_roomid(const char* value, size_t size) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CreateJoinRoomArgs::mutable_roomid() {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  return roomid_;
}
inline ::std::string* CreateJoinRoomArgs::release_roomid() {
  clear_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = roomid_;
    roomid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string ServerType = 2;
inline bool CreateJoinRoomArgs::has_servertype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateJoinRoomArgs::set_has_servertype() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateJoinRoomArgs::clear_has_servertype() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateJoinRoomArgs::clear_servertype() {
  if (servertype_ != &::google::protobuf::internal::kEmptyString) {
    servertype_->clear();
  }
  clear_has_servertype();
}
inline const ::std::string& CreateJoinRoomArgs::servertype() const {
  return *servertype_;
}
inline void CreateJoinRoomArgs::set_servertype(const ::std::string& value) {
  set_has_servertype();
  if (servertype_ == &::google::protobuf::internal::kEmptyString) {
    servertype_ = new ::std::string;
  }
  servertype_->assign(value);
}
inline void CreateJoinRoomArgs::set_servertype(const char* value) {
  set_has_servertype();
  if (servertype_ == &::google::protobuf::internal::kEmptyString) {
    servertype_ = new ::std::string;
  }
  servertype_->assign(value);
}
inline void CreateJoinRoomArgs::set_servertype(const char* value, size_t size) {
  set_has_servertype();
  if (servertype_ == &::google::protobuf::internal::kEmptyString) {
    servertype_ = new ::std::string;
  }
  servertype_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* CreateJoinRoomArgs::mutable_servertype() {
  set_has_servertype();
  if (servertype_ == &::google::protobuf::internal::kEmptyString) {
    servertype_ = new ::std::string;
  }
  return servertype_;
}
inline ::std::string* CreateJoinRoomArgs::release_servertype() {
  clear_has_servertype();
  if (servertype_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = servertype_;
    servertype_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional bool Visible = 3;
inline bool CreateJoinRoomArgs::has_visible() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CreateJoinRoomArgs::set_has_visible() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CreateJoinRoomArgs::clear_has_visible() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CreateJoinRoomArgs::clear_visible() {
  visible_ = false;
  clear_has_visible();
}
inline bool CreateJoinRoomArgs::visible() const {
  return visible_;
}
inline void CreateJoinRoomArgs::set_visible(bool value) {
  set_has_visible();
  visible_ = value;
}

// repeated .EECloud.KeyValuePair RoomData = 4;
inline int CreateJoinRoomArgs::roomdata_size() const {
  return roomdata_.size();
}
inline void CreateJoinRoomArgs::clear_roomdata() {
  roomdata_.Clear();
}
inline const ::EECloud::KeyValuePair& CreateJoinRoomArgs::roomdata(int index) const {
  return roomdata_.Get(index);
}
inline ::EECloud::KeyValuePair* CreateJoinRoomArgs::mutable_roomdata(int index) {
  return roomdata_.Mutable(index);
}
inline ::EECloud::KeyValuePair* CreateJoinRoomArgs::add_roomdata() {
  return roomdata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
CreateJoinRoomArgs::roomdata() const {
  return roomdata_;
}
inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
CreateJoinRoomArgs::mutable_roomdata() {
  return &roomdata_;
}

// repeated .EECloud.KeyValuePair JoinData = 5;
inline int CreateJoinRoomArgs::joindata_size() const {
  return joindata_.size();
}
inline void CreateJoinRoomArgs::clear_joindata() {
  joindata_.Clear();
}
inline const ::EECloud::KeyValuePair& CreateJoinRoomArgs::joindata(int index) const {
  return joindata_.Get(index);
}
inline ::EECloud::KeyValuePair* CreateJoinRoomArgs::mutable_joindata(int index) {
  return joindata_.Mutable(index);
}
inline ::EECloud::KeyValuePair* CreateJoinRoomArgs::add_joindata() {
  return joindata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
CreateJoinRoomArgs::joindata() const {
  return joindata_;
}
inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
CreateJoinRoomArgs::mutable_joindata() {
  return &joindata_;
}

// optional bool IsDevRoom = 6;
inline bool CreateJoinRoomArgs::has_isdevroom() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void CreateJoinRoomArgs::set_has_isdevroom() {
  _has_bits_[0] |= 0x00000020u;
}
inline void CreateJoinRoomArgs::clear_has_isdevroom() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void CreateJoinRoomArgs::clear_isdevroom() {
  isdevroom_ = false;
  clear_has_isdevroom();
}
inline bool CreateJoinRoomArgs::isdevroom() const {
  return isdevroom_;
}
inline void CreateJoinRoomArgs::set_isdevroom(bool value) {
  set_has_isdevroom();
  isdevroom_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace EECloud

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CreateJoinRoomArgs_2eproto__INCLUDED
