// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JoinRoomArgs.proto

#ifndef PROTOBUF_JoinRoomArgs_2eproto__INCLUDED
#define PROTOBUF_JoinRoomArgs_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "KeyValuePair.pb.h"
// @@protoc_insertion_point(includes)

namespace EECloud {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_JoinRoomArgs_2eproto();
void protobuf_AssignDesc_JoinRoomArgs_2eproto();
void protobuf_ShutdownFile_JoinRoomArgs_2eproto();

class JoinRoomArgs;

// ===================================================================

class JoinRoomArgs : public ::google::protobuf::Message {
 public:
  JoinRoomArgs();
  virtual ~JoinRoomArgs();
  
  JoinRoomArgs(const JoinRoomArgs& from);
  
  inline JoinRoomArgs& operator=(const JoinRoomArgs& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const JoinRoomArgs& default_instance();
  
  void Swap(JoinRoomArgs* other);
  
  // implements Message ----------------------------------------------
  
  JoinRoomArgs* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const JoinRoomArgs& from);
  void MergeFrom(const JoinRoomArgs& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional string RoomId = 1;
  inline bool has_roomid() const;
  inline void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  inline const ::std::string& roomid() const;
  inline void set_roomid(const ::std::string& value);
  inline void set_roomid(const char* value);
  inline void set_roomid(const char* value, size_t size);
  inline ::std::string* mutable_roomid();
  inline ::std::string* release_roomid();
  
  // repeated .EECloud.KeyValuePair JoinData = 2;
  inline int joindata_size() const;
  inline void clear_joindata();
  static const int kJoinDataFieldNumber = 2;
  inline const ::EECloud::KeyValuePair& joindata(int index) const;
  inline ::EECloud::KeyValuePair* mutable_joindata(int index);
  inline ::EECloud::KeyValuePair* add_joindata();
  inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
      joindata() const;
  inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
      mutable_joindata();
  
  // optional bool IsDevRoom = 3;
  inline bool has_isdevroom() const;
  inline void clear_isdevroom();
  static const int kIsDevRoomFieldNumber = 3;
  inline bool isdevroom() const;
  inline void set_isdevroom(bool value);
  
  // @@protoc_insertion_point(class_scope:EECloud.JoinRoomArgs)
 private:
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_isdevroom();
  inline void clear_has_isdevroom();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* roomid_;
  ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair > joindata_;
  bool isdevroom_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_JoinRoomArgs_2eproto();
  friend void protobuf_AssignDesc_JoinRoomArgs_2eproto();
  friend void protobuf_ShutdownFile_JoinRoomArgs_2eproto();
  
  void InitAsDefaultInstance();
  static JoinRoomArgs* default_instance_;
};
// ===================================================================


// ===================================================================

// JoinRoomArgs

// optional string RoomId = 1;
inline bool JoinRoomArgs::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JoinRoomArgs::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JoinRoomArgs::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JoinRoomArgs::clear_roomid() {
  if (roomid_ != &::google::protobuf::internal::kEmptyString) {
    roomid_->clear();
  }
  clear_has_roomid();
}
inline const ::std::string& JoinRoomArgs::roomid() const {
  return *roomid_;
}
inline void JoinRoomArgs::set_roomid(const ::std::string& value) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(value);
}
inline void JoinRoomArgs::set_roomid(const char* value) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(value);
}
inline void JoinRoomArgs::set_roomid(const char* value, size_t size) {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  roomid_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* JoinRoomArgs::mutable_roomid() {
  set_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    roomid_ = new ::std::string;
  }
  return roomid_;
}
inline ::std::string* JoinRoomArgs::release_roomid() {
  clear_has_roomid();
  if (roomid_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = roomid_;
    roomid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// repeated .EECloud.KeyValuePair JoinData = 2;
inline int JoinRoomArgs::joindata_size() const {
  return joindata_.size();
}
inline void JoinRoomArgs::clear_joindata() {
  joindata_.Clear();
}
inline const ::EECloud::KeyValuePair& JoinRoomArgs::joindata(int index) const {
  return joindata_.Get(index);
}
inline ::EECloud::KeyValuePair* JoinRoomArgs::mutable_joindata(int index) {
  return joindata_.Mutable(index);
}
inline ::EECloud::KeyValuePair* JoinRoomArgs::add_joindata() {
  return joindata_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >&
JoinRoomArgs::joindata() const {
  return joindata_;
}
inline ::google::protobuf::RepeatedPtrField< ::EECloud::KeyValuePair >*
JoinRoomArgs::mutable_joindata() {
  return &joindata_;
}

// optional bool IsDevRoom = 3;
inline bool JoinRoomArgs::has_isdevroom() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void JoinRoomArgs::set_has_isdevroom() {
  _has_bits_[0] |= 0x00000004u;
}
inline void JoinRoomArgs::clear_has_isdevroom() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void JoinRoomArgs::clear_isdevroom() {
  isdevroom_ = false;
  clear_has_isdevroom();
}
inline bool JoinRoomArgs::isdevroom() const {
  return isdevroom_;
}
inline void JoinRoomArgs::set_isdevroom(bool value) {
  set_has_isdevroom();
  isdevroom_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace EECloud

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_JoinRoomArgs_2eproto__INCLUDED
