// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SimpleRecoverPasswordArgs.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace EECloud {

namespace {

const ::google::protobuf::Descriptor* SimpleConnectArgs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SimpleConnectArgs_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_SimpleRecoverPasswordArgs_2eproto() {
  protobuf_AddDesc_SimpleRecoverPasswordArgs_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SimpleRecoverPasswordArgs.proto");
  GOOGLE_CHECK(file != NULL);
  SimpleConnectArgs_descriptor_ = file->message_type(0);
  static const int SimpleConnectArgs_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimpleConnectArgs, gameid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimpleConnectArgs, usernameoremail_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimpleConnectArgs, password_),
  };
  SimpleConnectArgs_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SimpleConnectArgs_descriptor_,
      SimpleConnectArgs::default_instance_,
      SimpleConnectArgs_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimpleConnectArgs, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SimpleConnectArgs, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SimpleConnectArgs));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SimpleRecoverPasswordArgs_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SimpleConnectArgs_descriptor_, &SimpleConnectArgs::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SimpleRecoverPasswordArgs_2eproto() {
  delete SimpleConnectArgs::default_instance_;
  delete SimpleConnectArgs_reflection_;
}

void protobuf_AddDesc_SimpleRecoverPasswordArgs_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037SimpleRecoverPasswordArgs.proto\022\007EEClo"
    "ud\"N\n\021SimpleConnectArgs\022\016\n\006GameId\030\001 \001(\t\022"
    "\027\n\017UsernameOrEmail\030\002 \001(\t\022\020\n\010Password\030\003 \001"
    "(\t", 122);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SimpleRecoverPasswordArgs.proto", &protobuf_RegisterTypes);
  SimpleConnectArgs::default_instance_ = new SimpleConnectArgs();
  SimpleConnectArgs::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SimpleRecoverPasswordArgs_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SimpleRecoverPasswordArgs_2eproto {
  StaticDescriptorInitializer_SimpleRecoverPasswordArgs_2eproto() {
    protobuf_AddDesc_SimpleRecoverPasswordArgs_2eproto();
  }
} static_descriptor_initializer_SimpleRecoverPasswordArgs_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int SimpleConnectArgs::kGameIdFieldNumber;
const int SimpleConnectArgs::kUsernameOrEmailFieldNumber;
const int SimpleConnectArgs::kPasswordFieldNumber;
#endif  // !_MSC_VER

SimpleConnectArgs::SimpleConnectArgs()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SimpleConnectArgs::InitAsDefaultInstance() {
}

SimpleConnectArgs::SimpleConnectArgs(const SimpleConnectArgs& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SimpleConnectArgs::SharedCtor() {
  _cached_size_ = 0;
  gameid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  usernameoremail_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  password_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SimpleConnectArgs::~SimpleConnectArgs() {
  SharedDtor();
}

void SimpleConnectArgs::SharedDtor() {
  if (gameid_ != &::google::protobuf::internal::kEmptyString) {
    delete gameid_;
  }
  if (usernameoremail_ != &::google::protobuf::internal::kEmptyString) {
    delete usernameoremail_;
  }
  if (password_ != &::google::protobuf::internal::kEmptyString) {
    delete password_;
  }
  if (this != default_instance_) {
  }
}

void SimpleConnectArgs::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SimpleConnectArgs::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SimpleConnectArgs_descriptor_;
}

const SimpleConnectArgs& SimpleConnectArgs::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SimpleRecoverPasswordArgs_2eproto();  return *default_instance_;
}

SimpleConnectArgs* SimpleConnectArgs::default_instance_ = NULL;

SimpleConnectArgs* SimpleConnectArgs::New() const {
  return new SimpleConnectArgs;
}

void SimpleConnectArgs::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_gameid()) {
      if (gameid_ != &::google::protobuf::internal::kEmptyString) {
        gameid_->clear();
      }
    }
    if (has_usernameoremail()) {
      if (usernameoremail_ != &::google::protobuf::internal::kEmptyString) {
        usernameoremail_->clear();
      }
    }
    if (has_password()) {
      if (password_ != &::google::protobuf::internal::kEmptyString) {
        password_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SimpleConnectArgs::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string GameId = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_gameid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->gameid().data(), this->gameid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_UsernameOrEmail;
        break;
      }
      
      // optional string UsernameOrEmail = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_UsernameOrEmail:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usernameoremail()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->usernameoremail().data(), this->usernameoremail().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(26)) goto parse_Password;
        break;
      }
      
      // optional string Password = 3;
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_Password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SimpleConnectArgs::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string GameId = 1;
  if (has_gameid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gameid().data(), this->gameid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->gameid(), output);
  }
  
  // optional string UsernameOrEmail = 2;
  if (has_usernameoremail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->usernameoremail().data(), this->usernameoremail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->usernameoremail(), output);
  }
  
  // optional string Password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->password(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SimpleConnectArgs::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string GameId = 1;
  if (has_gameid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->gameid().data(), this->gameid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->gameid(), target);
  }
  
  // optional string UsernameOrEmail = 2;
  if (has_usernameoremail()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->usernameoremail().data(), this->usernameoremail().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->usernameoremail(), target);
  }
  
  // optional string Password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SimpleConnectArgs::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string GameId = 1;
    if (has_gameid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->gameid());
    }
    
    // optional string UsernameOrEmail = 2;
    if (has_usernameoremail()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->usernameoremail());
    }
    
    // optional string Password = 3;
    if (has_password()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->password());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SimpleConnectArgs::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SimpleConnectArgs* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SimpleConnectArgs*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SimpleConnectArgs::MergeFrom(const SimpleConnectArgs& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_gameid()) {
      set_gameid(from.gameid());
    }
    if (from.has_usernameoremail()) {
      set_usernameoremail(from.usernameoremail());
    }
    if (from.has_password()) {
      set_password(from.password());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SimpleConnectArgs::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimpleConnectArgs::CopyFrom(const SimpleConnectArgs& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleConnectArgs::IsInitialized() const {
  
  return true;
}

void SimpleConnectArgs::Swap(SimpleConnectArgs* other) {
  if (other != this) {
    std::swap(gameid_, other->gameid_);
    std::swap(usernameoremail_, other->usernameoremail_);
    std::swap(password_, other->password_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SimpleConnectArgs::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SimpleConnectArgs_descriptor_;
  metadata.reflection = SimpleConnectArgs_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace EECloud

// @@protoc_insertion_point(global_scope)
