// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegistrationError.proto

#ifndef PROTOBUF_RegistrationError_2eproto__INCLUDED
#define PROTOBUF_RegistrationError_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace EECloud {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_RegistrationError_2eproto();
void protobuf_AssignDesc_RegistrationError_2eproto();
void protobuf_ShutdownFile_RegistrationError_2eproto();

class RegistrationError;

// ===================================================================

class RegistrationError : public ::google::protobuf::Message {
 public:
  RegistrationError();
  virtual ~RegistrationError();
  
  RegistrationError(const RegistrationError& from);
  
  inline RegistrationError& operator=(const RegistrationError& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegistrationError& default_instance();
  
  void Swap(RegistrationError* other);
  
  // implements Message ----------------------------------------------
  
  RegistrationError* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegistrationError& from);
  void MergeFrom(const RegistrationError& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 ErrorCode = 1;
  inline bool has_errorcode() const;
  inline void clear_errorcode();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 errorcode() const;
  inline void set_errorcode(::google::protobuf::int32 value);
  
  // optional string Message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  
  // optional string UsernameError = 3;
  inline bool has_usernameerror() const;
  inline void clear_usernameerror();
  static const int kUsernameErrorFieldNumber = 3;
  inline const ::std::string& usernameerror() const;
  inline void set_usernameerror(const ::std::string& value);
  inline void set_usernameerror(const char* value);
  inline void set_usernameerror(const char* value, size_t size);
  inline ::std::string* mutable_usernameerror();
  inline ::std::string* release_usernameerror();
  
  // optional string PasswordError = 4;
  inline bool has_passworderror() const;
  inline void clear_passworderror();
  static const int kPasswordErrorFieldNumber = 4;
  inline const ::std::string& passworderror() const;
  inline void set_passworderror(const ::std::string& value);
  inline void set_passworderror(const char* value);
  inline void set_passworderror(const char* value, size_t size);
  inline ::std::string* mutable_passworderror();
  inline ::std::string* release_passworderror();
  
  // optional string EmailError = 5;
  inline bool has_emailerror() const;
  inline void clear_emailerror();
  static const int kEmailErrorFieldNumber = 5;
  inline const ::std::string& emailerror() const;
  inline void set_emailerror(const ::std::string& value);
  inline void set_emailerror(const char* value);
  inline void set_emailerror(const char* value, size_t size);
  inline ::std::string* mutable_emailerror();
  inline ::std::string* release_emailerror();
  
  // optional string CaptchaError = 6;
  inline bool has_captchaerror() const;
  inline void clear_captchaerror();
  static const int kCaptchaErrorFieldNumber = 6;
  inline const ::std::string& captchaerror() const;
  inline void set_captchaerror(const ::std::string& value);
  inline void set_captchaerror(const char* value);
  inline void set_captchaerror(const char* value, size_t size);
  inline ::std::string* mutable_captchaerror();
  inline ::std::string* release_captchaerror();
  
  // @@protoc_insertion_point(class_scope:EECloud.RegistrationError)
 private:
  inline void set_has_errorcode();
  inline void clear_has_errorcode();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_usernameerror();
  inline void clear_has_usernameerror();
  inline void set_has_passworderror();
  inline void clear_has_passworderror();
  inline void set_has_emailerror();
  inline void clear_has_emailerror();
  inline void set_has_captchaerror();
  inline void clear_has_captchaerror();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* message_;
  ::std::string* usernameerror_;
  ::std::string* passworderror_;
  ::std::string* emailerror_;
  ::std::string* captchaerror_;
  ::google::protobuf::int32 errorcode_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  friend void  protobuf_AddDesc_RegistrationError_2eproto();
  friend void protobuf_AssignDesc_RegistrationError_2eproto();
  friend void protobuf_ShutdownFile_RegistrationError_2eproto();
  
  void InitAsDefaultInstance();
  static RegistrationError* default_instance_;
};
// ===================================================================


// ===================================================================

// RegistrationError

// optional int32 ErrorCode = 1;
inline bool RegistrationError::has_errorcode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RegistrationError::set_has_errorcode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RegistrationError::clear_has_errorcode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RegistrationError::clear_errorcode() {
  errorcode_ = 0;
  clear_has_errorcode();
}
inline ::google::protobuf::int32 RegistrationError::errorcode() const {
  return errorcode_;
}
inline void RegistrationError::set_errorcode(::google::protobuf::int32 value) {
  set_has_errorcode();
  errorcode_ = value;
}

// optional string Message = 2;
inline bool RegistrationError::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RegistrationError::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RegistrationError::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RegistrationError::clear_message() {
  if (message_ != &::google::protobuf::internal::kEmptyString) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& RegistrationError::message() const {
  return *message_;
}
inline void RegistrationError::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void RegistrationError::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void RegistrationError::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegistrationError::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    message_ = new ::std::string;
  }
  return message_;
}
inline ::std::string* RegistrationError::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string UsernameError = 3;
inline bool RegistrationError::has_usernameerror() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RegistrationError::set_has_usernameerror() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RegistrationError::clear_has_usernameerror() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RegistrationError::clear_usernameerror() {
  if (usernameerror_ != &::google::protobuf::internal::kEmptyString) {
    usernameerror_->clear();
  }
  clear_has_usernameerror();
}
inline const ::std::string& RegistrationError::usernameerror() const {
  return *usernameerror_;
}
inline void RegistrationError::set_usernameerror(const ::std::string& value) {
  set_has_usernameerror();
  if (usernameerror_ == &::google::protobuf::internal::kEmptyString) {
    usernameerror_ = new ::std::string;
  }
  usernameerror_->assign(value);
}
inline void RegistrationError::set_usernameerror(const char* value) {
  set_has_usernameerror();
  if (usernameerror_ == &::google::protobuf::internal::kEmptyString) {
    usernameerror_ = new ::std::string;
  }
  usernameerror_->assign(value);
}
inline void RegistrationError::set_usernameerror(const char* value, size_t size) {
  set_has_usernameerror();
  if (usernameerror_ == &::google::protobuf::internal::kEmptyString) {
    usernameerror_ = new ::std::string;
  }
  usernameerror_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegistrationError::mutable_usernameerror() {
  set_has_usernameerror();
  if (usernameerror_ == &::google::protobuf::internal::kEmptyString) {
    usernameerror_ = new ::std::string;
  }
  return usernameerror_;
}
inline ::std::string* RegistrationError::release_usernameerror() {
  clear_has_usernameerror();
  if (usernameerror_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = usernameerror_;
    usernameerror_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string PasswordError = 4;
inline bool RegistrationError::has_passworderror() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RegistrationError::set_has_passworderror() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RegistrationError::clear_has_passworderror() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RegistrationError::clear_passworderror() {
  if (passworderror_ != &::google::protobuf::internal::kEmptyString) {
    passworderror_->clear();
  }
  clear_has_passworderror();
}
inline const ::std::string& RegistrationError::passworderror() const {
  return *passworderror_;
}
inline void RegistrationError::set_passworderror(const ::std::string& value) {
  set_has_passworderror();
  if (passworderror_ == &::google::protobuf::internal::kEmptyString) {
    passworderror_ = new ::std::string;
  }
  passworderror_->assign(value);
}
inline void RegistrationError::set_passworderror(const char* value) {
  set_has_passworderror();
  if (passworderror_ == &::google::protobuf::internal::kEmptyString) {
    passworderror_ = new ::std::string;
  }
  passworderror_->assign(value);
}
inline void RegistrationError::set_passworderror(const char* value, size_t size) {
  set_has_passworderror();
  if (passworderror_ == &::google::protobuf::internal::kEmptyString) {
    passworderror_ = new ::std::string;
  }
  passworderror_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegistrationError::mutable_passworderror() {
  set_has_passworderror();
  if (passworderror_ == &::google::protobuf::internal::kEmptyString) {
    passworderror_ = new ::std::string;
  }
  return passworderror_;
}
inline ::std::string* RegistrationError::release_passworderror() {
  clear_has_passworderror();
  if (passworderror_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = passworderror_;
    passworderror_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string EmailError = 5;
inline bool RegistrationError::has_emailerror() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RegistrationError::set_has_emailerror() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RegistrationError::clear_has_emailerror() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RegistrationError::clear_emailerror() {
  if (emailerror_ != &::google::protobuf::internal::kEmptyString) {
    emailerror_->clear();
  }
  clear_has_emailerror();
}
inline const ::std::string& RegistrationError::emailerror() const {
  return *emailerror_;
}
inline void RegistrationError::set_emailerror(const ::std::string& value) {
  set_has_emailerror();
  if (emailerror_ == &::google::protobuf::internal::kEmptyString) {
    emailerror_ = new ::std::string;
  }
  emailerror_->assign(value);
}
inline void RegistrationError::set_emailerror(const char* value) {
  set_has_emailerror();
  if (emailerror_ == &::google::protobuf::internal::kEmptyString) {
    emailerror_ = new ::std::string;
  }
  emailerror_->assign(value);
}
inline void RegistrationError::set_emailerror(const char* value, size_t size) {
  set_has_emailerror();
  if (emailerror_ == &::google::protobuf::internal::kEmptyString) {
    emailerror_ = new ::std::string;
  }
  emailerror_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegistrationError::mutable_emailerror() {
  set_has_emailerror();
  if (emailerror_ == &::google::protobuf::internal::kEmptyString) {
    emailerror_ = new ::std::string;
  }
  return emailerror_;
}
inline ::std::string* RegistrationError::release_emailerror() {
  clear_has_emailerror();
  if (emailerror_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = emailerror_;
    emailerror_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}

// optional string CaptchaError = 6;
inline bool RegistrationError::has_captchaerror() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RegistrationError::set_has_captchaerror() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RegistrationError::clear_has_captchaerror() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RegistrationError::clear_captchaerror() {
  if (captchaerror_ != &::google::protobuf::internal::kEmptyString) {
    captchaerror_->clear();
  }
  clear_has_captchaerror();
}
inline const ::std::string& RegistrationError::captchaerror() const {
  return *captchaerror_;
}
inline void RegistrationError::set_captchaerror(const ::std::string& value) {
  set_has_captchaerror();
  if (captchaerror_ == &::google::protobuf::internal::kEmptyString) {
    captchaerror_ = new ::std::string;
  }
  captchaerror_->assign(value);
}
inline void RegistrationError::set_captchaerror(const char* value) {
  set_has_captchaerror();
  if (captchaerror_ == &::google::protobuf::internal::kEmptyString) {
    captchaerror_ = new ::std::string;
  }
  captchaerror_->assign(value);
}
inline void RegistrationError::set_captchaerror(const char* value, size_t size) {
  set_has_captchaerror();
  if (captchaerror_ == &::google::protobuf::internal::kEmptyString) {
    captchaerror_ = new ::std::string;
  }
  captchaerror_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RegistrationError::mutable_captchaerror() {
  set_has_captchaerror();
  if (captchaerror_ == &::google::protobuf::internal::kEmptyString) {
    captchaerror_ = new ::std::string;
  }
  return captchaerror_;
}
inline ::std::string* RegistrationError::release_captchaerror() {
  clear_has_captchaerror();
  if (captchaerror_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = captchaerror_;
    captchaerror_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace EECloud

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_RegistrationError_2eproto__INCLUDED
