// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LoadMyPlayerObjectOutput.proto

#ifndef PROTOBUF_LoadMyPlayerObjectOutput_2eproto__INCLUDED
#define PROTOBUF_LoadMyPlayerObjectOutput_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
#include "../../Helpers/DatabaseObject.pb.h"
// @@protoc_insertion_point(includes)

namespace EECloud {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_LoadMyPlayerObjectOutput_2eproto();
void protobuf_AssignDesc_LoadMyPlayerObjectOutput_2eproto();
void protobuf_ShutdownFile_LoadMyPlayerObjectOutput_2eproto();

class LoadMyPlayerObjectOutput;

// ===================================================================

class LoadMyPlayerObjectOutput : public ::google::protobuf::Message {
 public:
  LoadMyPlayerObjectOutput();
  virtual ~LoadMyPlayerObjectOutput();
  
  LoadMyPlayerObjectOutput(const LoadMyPlayerObjectOutput& from);
  
  inline LoadMyPlayerObjectOutput& operator=(const LoadMyPlayerObjectOutput& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const LoadMyPlayerObjectOutput& default_instance();
  
  void Swap(LoadMyPlayerObjectOutput* other);
  
  // implements Message ----------------------------------------------
  
  LoadMyPlayerObjectOutput* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoadMyPlayerObjectOutput& from);
  void MergeFrom(const LoadMyPlayerObjectOutput& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional .EECloud.DatabaseObject PlayerObject = 1;
  inline bool has_playerobject() const;
  inline void clear_playerobject();
  static const int kPlayerObjectFieldNumber = 1;
  inline const ::EECloud::DatabaseObject& playerobject() const;
  inline ::EECloud::DatabaseObject* mutable_playerobject();
  inline ::EECloud::DatabaseObject* release_playerobject();
  
  // @@protoc_insertion_point(class_scope:EECloud.LoadMyPlayerObjectOutput)
 private:
  inline void set_has_playerobject();
  inline void clear_has_playerobject();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::EECloud::DatabaseObject* playerobject_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_LoadMyPlayerObjectOutput_2eproto();
  friend void protobuf_AssignDesc_LoadMyPlayerObjectOutput_2eproto();
  friend void protobuf_ShutdownFile_LoadMyPlayerObjectOutput_2eproto();
  
  void InitAsDefaultInstance();
  static LoadMyPlayerObjectOutput* default_instance_;
};
// ===================================================================


// ===================================================================

// LoadMyPlayerObjectOutput

// optional .EECloud.DatabaseObject PlayerObject = 1;
inline bool LoadMyPlayerObjectOutput::has_playerobject() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoadMyPlayerObjectOutput::set_has_playerobject() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoadMyPlayerObjectOutput::clear_has_playerobject() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoadMyPlayerObjectOutput::clear_playerobject() {
  if (playerobject_ != NULL) playerobject_->::EECloud::DatabaseObject::Clear();
  clear_has_playerobject();
}
inline const ::EECloud::DatabaseObject& LoadMyPlayerObjectOutput::playerobject() const {
  return playerobject_ != NULL ? *playerobject_ : *default_instance_->playerobject_;
}
inline ::EECloud::DatabaseObject* LoadMyPlayerObjectOutput::mutable_playerobject() {
  set_has_playerobject();
  if (playerobject_ == NULL) playerobject_ = new ::EECloud::DatabaseObject;
  return playerobject_;
}
inline ::EECloud::DatabaseObject* LoadMyPlayerObjectOutput::release_playerobject() {
  clear_has_playerobject();
  ::EECloud::DatabaseObject* temp = playerobject_;
  playerobject_ = NULL;
  return temp;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace EECloud

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_LoadMyPlayerObjectOutput_2eproto__INCLUDED
